# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.3.7"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0.2"

# Speeds up boot time by caching expensive operations.
gem "bootsnap", require: false

# The asset pipeline is optional now.
# gem "sprockets-rails"

# Use postgresql as the database for Active Record
gem "pg", "~> 1.5"

# Use Puma as the app server
gem "puma", "~> 6.6"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
gem "rack-cors"

# Provides time zone data for Windows
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Authentication
gem 'devise'
gem 'devise-jwt'

# Serializers for JSON API
gem 'active_model_serializers', '~> 0.10.0'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false
end

group :development do
  # Use console on exceptions pages
  gem "web-console"

  # Add speed badges [https://github.com/noelrappin/rack-mini-profiler]
  gem "rack-mini-profiler"

  # A logger for ActiveRecord queries
  gem "logidze"
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem "capybara"
  gem "selenium-webdriver"

  # Easy installation and use of web drivers to run system tests with browsers
  gem "webdrivers", "= 5.3.0"
end

# To avoid breaking changes from rubyzip v3
gem "rubyzip", "~> 2.3.0"
