# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.3.7"

gem "rails", "~> 8.0.2"
gem "bootsnap", require: false
gem "pg", "~> 1.6"
gem "puma", "~> 6.6"
gem "rack-cors"
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

# Authentication
gem "devise"
gem "devise-jwt"

# Serializers for JSON API
gem "active_model_serializers", "~> 0.10.0"

# Avoid breaking changes from rubyzip v3
gem "rubyzip", "~> 2.3.0"

# Image generation and processing
gem "ruby-vips", "~> 2.1"
gem "mini_magick", "~> 5.0"

# Background job processing
gem "sidekiq", "~> 7.0"

# Caching
gem "redis", "~> 5.0"

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "rubocop-rails-omakase", require: false
  gem "brakeman", require: false
end

group :development do
  gem "web-console"
  gem "rack-mini-profiler"
  gem "logidze"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers", "= 5.3.0"
end
