# PostgreSQL database configuration for Chronicle Tree family tree API
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: chronicle_tree_api_development
  username: postgres
  password: 437897
  host: localhost
  port: 5432

test:
  <<: *default
  database: chronicle_tree_api_test
  username: postgres
  password: 437897
  host: localhost
  port: 5432

production:
  primary: &primary_production
    <<: *default
    database: chronicle_tree_api_production
    username: chronicle_tree_api
    password: <%= ENV["CHRONICLE_TREE_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: chronicle_tree_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: chronicle_tree_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: chronicle_tree_api_production_cable
    migrations_paths: db/cable_migrate
